# Generated by Django 4.1.7 on 2023-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='users_imp/user.jpg', upload_to='users_img'),
        ),
    ]
