# Generated by Django 4.1.7 on 2023-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_job_designation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
