# Generated by Django 4.1.7 on 2023-04-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_contact_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='users_documents'),
        ),
    ]
