# Generated by Django 4.1.7 on 2023-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('event_name', models.CharField(max_length=200)),
                ('committee_name', models.CharField(max_length=200)),
                ('Entry_fee', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
